channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.7.5

  - pip=20.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==11.1.3 # https://rpaframework.org/releasenotes.html
    - fpdf2==2.4.5 # pip package to work with PDF Files in Python
    - pillow==8.3.1 # library to work with images useed for resizing image
